apiVersion: v1
kind: Service
metadata:
  name: gitops-demo-app-service
  namespace: dev
  labels:
    app: gitops-demo-app
    environment: dev
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: gitops-demo-app
    environment: dev
  sessionAffinity: None
