apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app-dev
  labels:
    app: example-app-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: example-app-dev
  template:
    metadata:
      labels:
        app: example-app-dev
    spec:
      containers:
      - name: nginx
        image: nginx:1.23
        ports:
        - containerPort: 80

