apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo-app
  namespace: prod
  labels:
    app: gitops-demo-app
    environment: prod
    version: v1.0.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gitops-demo-app
      environment: prod
  template:
    metadata:
      labels:
        app: gitops-demo-app
        environment: prod
        version: v1.0.0
    spec:
      containers:
      - name: gitops-demo-app
        image: gitops-demo-app:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: APP_VERSION
          value: "v1.0.0"
        - name: PORT
          value: "3000"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1001
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
