apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-dev-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/appgaua/demo.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 10
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-prod-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/appgaua/demo.git
    targetRevision: HEAD
    path: prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 10
