apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app-prod
  labels:
    app: example-app-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: example-app-prod
  template:
    metadata:
      labels:
        app: example-app-prod
    spec:
      containers:
      - name: nginx
        image: nginx:1.22
        ports:
        - containerPort: 80

